In [78]:
import pandas as pd

import tensorflow as tf
physical_devices = tf.config.experimental.list_physical_devices('GPU')
if len(physical_devices) > 0:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [152]:
df = pd.read_csv('Bank_Customers.csv')

y = df.iloc[:, -1].values
X = df.iloc[:, 3:-1].values

In [153]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [154]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [155]:
le = LabelEncoder()
le.fit(X[:, 2])

LabelEncoder()

In [156]:
le.classes_

array(['Female', 'Male'], dtype=object)

In [157]:
ct = ColumnTransformer(
     # Transformer name, Transformer Object and columns
    [
        ("country", OneHotEncoder(), [1])
     ],
    # Any other columns are ignored
    remainder="passthrough"
  )

In [158]:
X[:, 2]= le.fit_transform(X[:, 2])

In [159]:
ct.fit(X)

ColumnTransformer(remainder='passthrough',
                  transformers=[('country', OneHotEncoder(), [1])])

In [160]:
X_tran = ct.fit_transform(X)

In [164]:
X_tran[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [146]:
Sc = StandardScaler()
Sc.fit(X_tran)

StandardScaler()

In [147]:
X_tran = Sc.fit_transform(X_tran)

In [151]:
X_tran

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [123]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_tran, y, test_size=0.4, random_state=0)

In [124]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.losses import binary_crossentropy

model = Sequential()

model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

In [125]:
model.fit(x=X_train, y=y_train, batch_size=100
          , epochs=30, verbose=1)

Epoch 1/30
60/60 [==============================] - 1s 11ms/step - loss: 0.5332 - accuracy: 0.7975
Epoch 2/30
60/60 [==============================] - 1s 9ms/step - loss: 0.4160 - accuracy: 0.8208
Epoch 3/30
60/60 [==============================] - 1s 9ms/step - loss: 0.3731 - accuracy: 0.8492
Epoch 4/30
60/60 [==============================] - 1s 9ms/step - loss: 0.3491 - accuracy: 0.8597
Epoch 5/30
60/60 [==============================] - 1s 10ms/step - loss: 0.3349 - accuracy: 0.8650
Epoch 6/30
60/60 [==============================] - 1s 10ms/step - loss: 0.3351 - accuracy: 0.8637
Epoch 7/30
60/60 [==============================] - 1s 9ms/step - loss: 0.3259 - accuracy: 0.8685
Epoch 8/30
60/60 [==============================] - 1s 8ms/step - loss: 0.3236 - accuracy: 0.8712
Epoch 9/30
60/60 [==============================] - 1s 9ms/step - loss: 0.3211 - accuracy: 0.8712
Epoch 10/30
60/60 [==============================] - 1s 10ms/step - loss: 0.3132 - accuracy: 0.8733
Epoch 11/30
60/

In [126]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.44680431485176086
Test accuracy: 0.8454999923706055


In [165]:
TestSample = [[0,0,1,600, 1, 40, 3, 60000, 2, 1, 1, 50000]]
TestSample = Sc.fit_transform(TestSample)

In [167]:
prediction = model.predict(TestSample)

1/1 [==============================] - 0s 24ms/step


In [168]:
classes = ['NOT EXIT', 'EXIT']
MaxPosition=np.argmax(prediction)  
prediction_label=classes[MaxPosition]
print(prediction_label)

<IPython.core.display.Javascript object>

NOT EXIT
